### ISSUE TITLE
[Bug]: Traceback when run merge

### ISSUE THREAD

**Issue by lognece** [vzhd1701/csv2notion#15]
### csv2notion version

0.3.6.

### What OS are you using?

Linux

### OS Version / Linux distribution

Ubuntu 22.04.1 LTS

### Bug description

I use 
`poetry run csv2notion --token [here] --url "[here]" --merge [file].csv
`
and it gives me this traceback (in the log)

I already used csv2notion 2 weeks ago with the same command and it worked perfectly so I don't know what happened.

### Log excerpt

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lognece/csv2notion/csv2notion/cli.py", line 82, in main
    cli(*sys.argv[1:])
  File "/home/lognece/csv2notion/csv2notion/cli.py", line 31, in cli
    client = get_notion_client(
  File "/home/lognece/csv2notion/csv2notion/notion_db.py", line 201, in get_notion_client
    client = NotionClientExtended(token_v2=token)
  File "/home/lognece/csv2notion/csv2notion/notion_db_client.py", line 23, in __init__
    super().__init__(*args, **kwargs)
  File "/home/lognece/.cache/pypoetry/virtualenvs/csv2notion-1cy6-Njf-py3.10/lib/python3.10/site-packages/notion/client.py", line 113, in __init__
    self._update_user_info()
  File "/home/lognece/.cache/pypoetry/virtualenvs/csv2notion-1cy6-Njf-py3.10/lib/python3.10/site-packages/notion/client.py", line 145, in _update_user_info
    if not records["space"]:
KeyError: 'space'
```

**Comment by sivagao** [comment]
same
