### ISSUE TITLE
[Bug]: TRaceback in --merge

### ISSUE THREAD

**Issue by ronaldulate** [vzhd1701/csv2notion#16]
### csv2notion version

0.3.7

### What OS are you using?

Windows

### OS Version / Linux distribution

Win11 22H2 22621.963

### Bug description

I use
csv2notion --token [my_token] --url [my_url] --icon-column icon_url --icon-column-keep --merge --randomize-select-colors [file].csv

### Log excerpt

```shell
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Scripts\csv2notion.exe\__main__.py", line 7, in <module>
  File "C:\Python311\Lib\site-packages\csv2notion\cli.py", line 82, in main
    cli(*sys.argv[1:])
  File "C:\Python311\Lib\site-packages\csv2notion\cli.py", line 31, in cli
    client = get_notion_client(
             ^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\csv2notion\notion_db.py", line 204, in get_notion_client
    client = NotionClientExtended(token_v2=token)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\csv2notion\notion_db_client.py", line 23, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Python311\Lib\site-packages\notion\client.py", line 88, in __init__
    self.session = create_session(client_specified_retry)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\notion\client.py", line 47, in create_session
    retry = Retry(
            ^^^^^^
TypeError: Retry.__init__() got an unexpected keyword argument 'allowed_methods'
```

**Comment by vzhd1701** [comment]
You have a dependency version conflict. You should install csv2notion in a virtual environment.

**Comment by ronaldulate** [comment]
thanks now work perfectly!
